---
simulation_config:
  time_seconds: !!int 10 # Tiempos de ejecución
  count_file_min: !!int 500 # Cantidad mínima de archivos
  count_file_max: !!int 1000 # Cantidad máxima de archivos

details_name_files:
  prefix: !!str "APL"
  separator: !!str "-0000"
  sequence_min: !!int 1
  sequence_max: !!int 1000
  extension: !!str ".log"

control_errors:
  no_found_reports: !!str 'No files found to generate report'

mission_options:
  OrbitOne: !!str "ORBONE"
  ColonyMoon: !!str "CLNM"
  VacMars: !!str "TMRS"
  GalaxyTwo: !!str "GALXONE"
  Unknown: !!str "UNKN"

option_status: 
  - "excellent"
  - "good"
  - "warning"
  - "faulty"
  - "killed"
  - "unknown"

option_device:
  - "satellites"
  - "airplanes"
  - "suits"
  - "vehicles"

date_format: "%d-%m-%Y %H:%M:%S"

spacecraft_options:
  name_default: !!str "-----APOLLO 11 SPACECRAFT-----"
  slogan_default: !!str "To infinity and beyond!!!"
  name_nasa: !!str "-----NASA'S APOLLO 11 SPACECRAFT-----"
  slogan_nasa: !!str "We are an impossibility in an impossible universe. (Ray Bradbury)"
  name_rocket: !!str "-----APOLLO 11 SPACECRAFT IN CO ROCKET ASSOCIATION-----"
  slogan_rocket: !!str "Somewhere, something incredible is waiting to be discovered. (Carl Sagan)"
  


